233 refactor browser
chStaiger/iBridges-Gui pull request #235
Opened 2024-07-25 06:14 UTC by chStaiger

I am not completely finished, the up and download buttons and their functionality need to be revised. But input on the rest is already very warmely welcome!!!!

- More responsiveness during browsing, caching implemented through flags
- Remove button to top
- ACL edits dependiing now on options specific to collection or data object
- Port sync to ibridges 1.0.1

2024-08-05 14:32 UTC, qubixes requested changes
The browser is so snappy since the last time I showed it off! I don't know if it's in this PR, but I love it!

2024-08-06 11:14 UTC, chStaiger commented on ibridgesgui/browser.py
> +        self.update_input_path(self.home_coll)
The little home button is also using thos function ... so yes, we need it in two places.

2024-08-06 11:15 UTC, chStaiger commented on ibridgesgui/browser.py
> +    def set_input_path_to_parent(self):
But this one is also used by a button, the little up-arrow button.

2024-08-06 11:16 UTC, chStaiger commented on ibridgesgui/browser.py
> +                        download(self.session, path, download_dir, overwrite=True)
For convenience during the development ;) It is outdated wuth the latest commits.

2024-08-06 11:21 UTC, chStaiger commented on ibridgesgui/threads.py
> +            An object containing four attributes:
I adjusted the doc string and referred to the ibridges docs.

2024-08-06 11:26 UTC, chStaiger commented
I finished the makeover of the upload and download buttons. I am not completely happy yet:
- The QDialog window stays on top of the main window and cannot be sent to the backend
- As long as the QDialog is open one cannot use the other features of the browser

As a workaround I made a utton to close the window while the data transfers are running in the backend. The logs accumulate the information what was successful and what not.

I think in a new PR we can have a look how to create a process ID for those closed windows and accumulate the concerning logging in a report.

2024-08-06 14:18 UTC, qubixes reviewed
I have found two things: When downloading a folder, the transfers are all done separately according to the log. This might be a bit slow? The metadata checkbox in the up/download is also unclear, it just gives the file that it will be saved to I suppose?

2024-08-06 16:04 UTC, chStaiger commented on ibridgesgui/gui_utils.py
> +    ops.upload = set().union(*[o.upload for o in operations])
Done!!! Thanks for pointing it out.

2024-08-06 16:26 UTC, merged